#!/usr/bin/env python

import os
import sys

if __name__ == "__main__":
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
    from needy.__main__ import main
    sys.exit(main(sys.argv))
